version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - jupyter_data:/home/app/.jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
    command: >
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --NotebookApp.token='' 
      --NotebookApp.password=''
      --NotebookApp.allow_origin='*'
      --NotebookApp.disable_check_xsrf=True
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a separate service for running tests
  test:
    build: .
    volumes:
      - .:/app
    command: >
      pytest --cov=. --cov-report=html
    profiles:
      - testing

volumes:
  jupyter_data:
